Mobile Display Keystrokes

Do you remember the old mobile display keyboards? Do you also remember how inconvenient it was to write on it?
Well, here you have to calculate how much keystrokes you have to do for a specific word.

This is the layout:



Return the amount of keystrokes of input str (! only letters, digits and special characters in lowercase included in layout without whitespaces !)

eg:

mobileKeyboard("123") => 3 (1+1+1)
mobileKeyboard("abc") => 9 (2+3+4)
mobileKeyboard("codewars") => 26 (4+4+2+3+2+2+4+5)

SOLUTION:

const trans = {'1234567890*#':1,
               'adgjmptw':2,
               'behknqux':3,
               'cfilorvy':4,
               'sz':5}

function mobileKeyboard(str){
  return str.split('')
            .map(e=>trans[
                         Object.keys(trans)
                               .filter(p=>p.includes(e))
                         ]
                 ).reduce((x,y)=>x+y,0)
}